name: Release

on:
#  push:
#    branches:
#      - main
#    paths:
#      - .github/workflows/release.yml
  release:
    types: [published, edited, released, prereleased]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-x86_64
          - macos-arm64
          - linux-x86_64
        php:
          - 8.1
          - 8.2
          - 8.3
        phar:
          - php-cs-fixer
    steps:
      - name: Download ${{ matrix.phar }} on ${{ matrix.platform }}
        id: download
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ matrix.phar }}-${{ matrix.php }}-${{ matrix.platform }}
          #commit: ${{ github.event.pull_request.head.sha }}
          search_artifacts: true

      - run: |
          pwd
          ls -lh .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.phar }}-${{ matrix.php }}-${{ matrix.platform }}
          asset_name: ${{ matrix.phar }}-${{ matrix.php }}-${{ matrix.platform }}
          asset_content_type: application/octet-stream
